apiVersion: v1
kind: Service
metadata:
  name: {{ include "aitdevops-site.fullname" . }}-order-service
  labels:
    app.kubernetes.io/name: {{ include "aitdevops-site.name" . }}
    helm.sh/chart: {{ include "aitdevops-site.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.orderService.service.type }}
  ports:
  - port: {{ .Values.orderService.service.port }}
    targetPort: {{ .Values.orderService.service.port }}
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "aitdevops-site.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "aitdevops-site.fullname" . }}-product-service
  labels:
    app.kubernetes.io/name: {{ include "aitdevops-site.name" . }}
    helm.sh/chart: {{ include "aitdevops-site.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.productService.service.type }}
  ports:
  - port: {{ .Values.productService.service.port }}
    targetPort: {{ .Values.productService.service.port }}
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "aitdevops-site.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "aitdevops-site.fullname" . }}-user-service
  labels:
    app.kubernetes.io/name: {{ include "aitdevops-site.name" . }}
    helm.sh/chart: {{ include "aitdevops-site.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.userService.service.type }}
  ports:
  - port: {{ .Values.userService.service.port }}
    targetPort: {{ .Values.userService.service.port }}
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "aitdevops-site.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
