apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aitdevops-site.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "aitdevops-site.name" . }}
    helm.sh/chart: {{ include "aitdevops-site.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aitdevops-site.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "aitdevops-site.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}
        ports:
        - containerPort: {{ .Values.frontend.service.port }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aitdevops-site.fullname" . }}-order-service
  labels:
    app.kubernetes.io/name: {{ include "aitdevops-site.name" . }}
    helm.sh/chart: {{ include "aitdevops-site.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aitdevops-site.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "aitdevops-site.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: order-service
        image: {{ .Values.orderService.image }}
        ports:
        - containerPort: {{ .Values.orderService.service.port }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aitdevops-site.fullname" . }}-product-service
  labels:
    app.kubernetes.io/name: {{ include "aitdevops-site.name" . }}
    helm.sh/chart: {{ include "aitdevops-site.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aitdevops-site.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "aitdevops-site.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: product-service
        image: {{ .Values.productService.image }}
        ports:
        - containerPort: {{ .Values.productService.service.port }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aitdevops-site.fullname" . }}-user-service
  labels:
    app.kubernetes.io/name: {{ include "aitdevops-site.name" . }}
    helm.sh/chart: {{ include "aitdevops-site.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aitdevops-site.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "aitdevops-site.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: user-service
        image: {{ .Values.userService.image }}
        ports:
        - containerPort: {{ .Values.userService.service.port }}
