apiVersion: v1
kind: Service
metadata:
  name: {{ include "aitdevops-site.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "aitdevops-site.name" . }}
    helm.sh/chart: {{ include "aitdevops-site.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.port }}
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "aitdevops-site.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
