apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/aitdevops/aitdevops-gke.git
  branch: flux
  secretRef:
    name: flux-system

