apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: aitdevops
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/aitdevops-cluster"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client

