name: CI Pipeline

on:
  push:
    branches:
      - argocd

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: kubectl

    - name: Configure Docker for GCP
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and push frontend image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/aitdevops-gke/frontend:${{ env.IMAGE_TAG }} -f frontend/Dockerfile ./frontend
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/aitdevops-gke/frontend:${{ env.IMAGE_TAG }}

    - name: Build and push order-service image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/aitdevops-gke/order-service:${{ env.IMAGE_TAG }} -f services/order-service/Dockerfile ./services/order-service
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/aitdevops-gke/order-service:${{ env.IMAGE_TAG }}

    - name: Build and push product-service image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/aitdevops-gke/product-service:${{ env.IMAGE_TAG }} -f services/product-service/Dockerfile ./services/product-service
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/aitdevops-gke/product-service:${{ env.IMAGE_TAG }}

    - name: Build and push user-service image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/aitdevops-gke/user-service:${{ env.IMAGE_TAG }} -f services/user-service/Dockerfile ./services/user-service
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/aitdevops-gke/user-service:${{ env.IMAGE_TAG }}

  update-manifest:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Helm values with new image tags
      run: |
        sed -i 's@\(us-central1-docker.pkg.dev/aitdevops8/aitdevops-gke/frontend:\).*@\1${{ env.IMAGE_TAG }}@g' charts/aitdevops-site/values.yaml
        sed -i 's@\(us-central1-docker.pkg.dev/aitdevops8/aitdevops-gke/order-service:\).*@\1${{ env.IMAGE_TAG }}@g' charts/aitdevops-site/values.yaml
        sed -i 's@\(us-central1-docker.pkg.dev/aitdevops8/aitdevops-gke/product-service:\).*@\1${{ env.IMAGE_TAG }}@g' charts/aitdevops-site/values.yaml
        sed -i 's@\(us-central1-docker.pkg.dev/aitdevops8/aitdevops-gke/user-service:\).*@\1${{ env.IMAGE_TAG }}@g' charts/aitdevops-site/values.yaml

    - name: Commit changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "github-actions"
        git add charts/aitdevops-site/values.yaml
        git commit -m "Update image tags to ${{ env.IMAGE_TAG }}"
        git push origin argocd
